export default {
    ADD_REPO: 'search/ADD_REPO',
    REMOVE_REPO: 'search/REMOVE_REPO',

    GET_LATEST_RELEASE_START: 'search/GET_LATEST_RELEASE_START',
    GET_LATEST_RELEASE: 'search/GET_LATEST_RELEASE',
    GET_LATEST_RELEASE_SUCCESS: 'search/GET_LATEST_RELEASE_SUCCESS',
    GET_LATEST_RELEASE_FAIL: 'search/GET_LATEST_RELEASE_FAIL',

    GET_RESULTS_START: 'search/GET_RESULTS_START',
    GET_RESULTS: 'search/GET_RESULTS',
    GET_RESULTS_SUCCESS: 'search/GET_RESULTS_SUCCESS',
    GET_RESULTS_FAIL: 'search/GET_RESULTS_FAIL',

    SET_QUERY: 'search/SET_QUERY',
};
