export default {
    ADD_REPO: 'search/ADD_REPO',
    REMOVE_REPO: 'search/REMOVE_REPO',

    GET_LATEST_RELEASE_START: 'search/GET_LATEST_RELEASE_START',
    GET_LATEST_RELEASE: 'search/GET_LATEST_RELEASE',
    GET_LATEST_RELEASE_SUCCESS: 'search/GET_LATEST_RELEASE_SUCCESS',
    GET_LATEST_RELEASE_FAIL: 'search/GET_LATEST_RELEASE_FAIL',

    SET_QUERY_START: 'search/SET_QUERY_START',
    SET_QUERY: 'search/SET_QUERY',
    SET_QUERY_SUCCESS: 'search/SET_QUERY_SUCCESS',
    SET_QUERY_FAIL: 'search/SET_QUERY_FAIL',
};
