export default {
    ADD_REPO: 'search/ADD_REPO',
    REMOVE_REPO: 'search/REMOVE_REPO',
    SET_RELEASE_NOTES: 'search/SET_RELEASE_NOTES',
    SET_QUERY: 'search/SET_QUERY',
    UPDATE_RELEASE_NOTES: 'search/UPDATE_RELEASE_NOTES',

    REFRESH_PAGE_START: 'search/REFRESH_PAGE_START',
    REFRESH_PAGE: 'search/REFRESH_PAGE',
    REFRESH_PAGE_SUCCESS: 'search/REFRESH_PAGE_SUCCESS',
    REFRESH_PAGE_FAIL: 'search/REFRESH_PAGE_FAIL',

    GET_LATEST_RELEASE_START: 'search/GET_LATEST_RELEASE_START',
    GET_LATEST_RELEASE: 'search/GET_LATEST_RELEASE',
    GET_LATEST_RELEASE_SUCCESS: 'search/GET_LATEST_RELEASE_SUCCESS',
    GET_LATEST_RELEASE_FAIL: 'search/GET_LATEST_RELEASE_FAIL',

    GET_RESULTS_START: 'search/GET_RESULTS_START',
    GET_RESULTS: 'search/GET_RESULTS',
    GET_RESULTS_SUCCESS: 'search/GET_RESULTS_SUCCESS',
    GET_RESULTS_FAIL: 'search/GET_RESULTS_FAIL',
};
